#!/bin/bash

echo "Installing alacritty..."

rm -f ~/.config/alacritty
ln -s $(pwd)/alacritty ~/.config/alacritty

echo "Installing starship..."

rm -f ~/.config/starship.toml
ln -s $(pwd)/starship.toml ~/.config/starship.toml

echo "Installing nvim..."

rm -f ~/.config/nvim
ln -s $(pwd)/nvim ~/.config/nvim

echo "Installing tmux..."

rm -f ~/.tmux.conf
ln -s $(pwd)/.tmux.conf ~/.tmux.conf
