#!/bin/bash

echo "Installing alacritty..."

rm -f ~/.config/alacritty
ln -s $(pwd)/alacritty ~/.config/alacritty

echo "Installing fish..."

rm -f ~/.config/fish
ln -s $(pwd)/fish ~/.config/fish

echo "Installing tmux..."

rm -f ~/.tmux.conf
ln -s $(pwd)/.tmux.conf ~/.tmux.conf

echo "Installing nvim..."

rm -f ~/.config/nvim
ln -s $(pwd)/nvim ~/.config/nvim

echo "Installing zellij..."

rm -f ~/.config/zellij
ln -s $(pwd)/zellij ~/.config/zellij

